### ISSUE TITLE
Flex Playground needs styling changes for dark mode

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#105]
Hi,

I didn't take the time to fix this, as it needs a lot of changes it seems. I might be wrong, but it's definitely not just a simple tweak of one or two CSS attributes. Maybe @hawkeye64 might know how to improve it without a lot of work. 

Scott

**Comment by IlCallo** [comment]
You know we cannot merge in dark mode with some pages/components of the docs not supporting it, right?
This is exactly we said we didn't want to work on it right now

**Comment by smolinari** [comment]
Ok. I've fixed it too. Was easier than I thought. 

Scott

**Comment by IlCallo** [comment]
Fixed into #104
