### ISSUE TITLE
Readability problems into dark mode

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#106]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Some components haven't been properly updated to support dark mode, here's a few screenshots

The white line here in every component page
![image](https://user-images.githubusercontent.com/10036108/155349889-b7a5d2d3-bb7a-43c6-b6f1-acd227e7d682.png)

Many sponsors logo aren't readable on a dark background
![image](https://user-images.githubusercontent.com/10036108/155350189-e08dcf53-f5f3-4f6b-b5b3-af9c2a157239.png)

The "show more" button of the nested installation item isn't visible
![image](https://user-images.githubusercontent.com/10036108/155350550-88c1c64b-4093-4230-a05e-d1cb2e7a38a1.png)

The code background color  must be updated as there isn't enough contrast right now
![image](https://user-images.githubusercontent.com/10036108/155350974-9fca77b4-ecc0-4c7a-b263-0b2d0a19a717.png)

Into why donate page, images aren't readable now
![image](https://user-images.githubusercontent.com/10036108/155351536-d32e78b6-215a-45e3-96c8-b628de4ba09a.png)

Quick navigation buttons aren't properly styled as dark
![image](https://user-images.githubusercontent.com/10036108/155351783-bee9defb-b92e-408f-b249-71b961dcaef2.png)

The inline code highlight doesn't really work into the "notes" boxes
![image](https://user-images.githubusercontent.com/10036108/155351925-868f826a-ccce-426d-9a2c-b284c5ff28bc.png)

Shadows aren't visible
![image](https://user-images.githubusercontent.com/10036108/155352492-ff95ccec-8cb5-4d79-860e-e7f9337ae34f.png)

Into flexbox guide, some writings aren't visible
![image](https://user-images.githubusercontent.com/10036108/155352710-6eb2a7c5-5601-406c-b81b-5c47d2720890.png)

We reached "Layout & Grid" page doing our checks
Please check other pages too

**Comment by smolinari** [comment]
I think I have most of these. There isn't much we can do about the shadows. 

I'm still tweaking... 😁 

Scott

**Comment by IlCallo** [comment]
We should probably invert the shadow colour depending on the dark mode flag

**Comment by smolinari** [comment]
Getting the shadows "switched" is not that easy (for me). 

I've done some more tweaking. The API section looks ok, I'd say.

![image](https://user-images.githubusercontent.com/3314957/155686798-5cf55228-2cdf-4a37-b5c9-43683aaf1e22.png)

Scott
