### ISSUE TITLE
Landing page bug with sponsors on Firefox

### ISSUE THREAD

**Issue by NiccoloMenozzi** [dreamonkey/quasar#112]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Things overlap badly here on MacOS Firefox. Check the mockup.
<img width="1440" alt="Schermata 2022-02-25 alle 14 39 36" src="https://user-images.githubusercontent.com/84564560/155724946-decfd216-4717-4548-aaea-33375c3fec3d.png">

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

[](https://quasar.beget.it/)

**Comment by IlCallo** [comment]
Known problem, has been fixed into #18
