### ISSUE TITLE
Expanded header should shrink more easily

### ISSUE THREAD

**Issue by ldiebold** [dreamonkey/quasar#116]
**Description**
When scrolling down the header gets smaller, however it feels like this happens too late (after scrolling about 300px).
I think it should be more like 50px.

Same concept with scrolling up. Once I've scrolled down the page, it's furstrating when the header expands again after scrolling up a bit.

**Website Section URL**
Docs

**Comment by IlCallo** [comment]
Are you sure you're seeing the last version of the docs?
Currently the header shrinks at 64px of scrolling down and expands at 200px of scrolling up.
Would you mind testing out the changes you propose and send a PR with the updated values?

You can change these values from

`docs/src/assets/landing-page/constants.js`
![image](https://user-images.githubusercontent.com/10036108/155968949-b3fa3d40-bb32-4498-98d2-a766c0f91305.png)

`docs/src/components/header/MainLayoutHeader.vue`
![image](https://user-images.githubusercontent.com/10036108/155969040-02bc7772-8b25-4035-b818-b43319712a90.png)
