### ISSUE TITLE
Put together a "Quick Start" Page/ Guide

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#117]
@IlCallo - I'd like to do the Quick Start page. But, I'm now not certain if it fits in the plan, since we are making the site public to some people. Or, can we still add things? 

Basically the idea is to give someone a simple path to get started with Quasar quickly. From there, I'd also send the user on their way to different parts of the docs, depending on their level of ability. 

So, I guess I'm asking, should I do the Quick Start page or not now?

Scott

**Comment by smolinari** [comment]
Working on this now. 

Scott

**Comment by IlCallo** [comment]
Reporting my answer from DM here, since I didn't had access to a PC during the weekend

> As far as it doesn't involve me or Nick and the team is ok with it, there's no problem
> We already discussed it 2 meetings ago and IIRC we said it's ok and we'll link it from the "get started" card directly
> No problem doing changes to content in this phase, me and Nick are only against UI/UX changes until we get some feedback from the community
