### ISSUE TITLE
Fix image background in dark mode

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#118]
My original solution for adding background color to the images breaks the images in some areas. Need to make a more specific solution for images needing a background, leaving other images unchanged. 

Scott

**Comment by IlCallo** [comment]
Where are these problems? Just to know if we need to fix this before the release or if it's just a side-problem
Eg. if it's a problem on the landing page we need to fix it asap, if it's hidden into some less used docs page, we can add a workaround and fix it later on

**Comment by smolinari** [comment]
The 404 page is one problem. The icon genie logo on the icon genie page is another.

Scott
