### ISSUE TITLE
Change hands images with new version

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#16]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Change the hands with the new .png with the better countour cropping

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL below_

Example: https://quasar.beget.it/introduction-to-quasar

**Comment by n05la3** [comment]
@NiccoloMenozzi, please can you confirm that these images have been changed? I think these images were changed without me realizing this issue was there.

**Comment by IlCallo** [comment]
There should be a new version where you found the previous ones, can you check those?

**Comment by NiccoloMenozzi** [comment]
@n05la3 the new images are here Dreamonkey/Tecnico/Clienti/Quasar/Design/Impaginati/Website/Executives/Images/Homepage background images
we discussed it some time ago. Same png, same name, different image with a better cropping.

**Comment by n05la3** [comment]
Okay sure, will do that. I was asking beceause I recently changed them after @NiccoloMenozzi told me to do so.

**Comment by NiccoloMenozzi** [comment]
yep, we need those new. Callo created the issue here but the first report was mine because I saw that no one already pushed the change.

**Comment by IlCallo** [comment]
Remember the hands should go vertical-layers-wise between the stars background and the text
Currently they're above the text
