### ISSUE TITLE
Add integration page

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#20]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

"Discover integrations" page is missing, must be implemented as we now have the mockups

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Docs

**Comment by smolinari** [comment]
What is considered an integration? Just wondering, as it isn't clear to me.

Scott

**Comment by IlCallo** [comment]
Quasar modes, but with a more understandable name

It's the page which contains this logos and links
![image](https://user-images.githubusercontent.com/10036108/153185617-43c7a781-a8e0-4e28-b875-1b39b2dfc58e.png)

and is connected to this card 
![image](https://user-images.githubusercontent.com/10036108/153185719-878a5da1-4e75-4bcc-add8-9b42ca2ace11.png)

**Comment by smolinari** [comment]
Ok. Got it. However, it's more about "One code base, multiple platforms". The topic, or rather what Quasar offers, is platform build targets. Integration, to me, has a different meaning. More like about this....

https://en.wikipedia.org/wiki/System_integration

Scott

**Comment by IlCallo** [comment]
"platforms" doesn't include "PWA", "SSR", "SPA", "BEX" tho, and we know many still think Quasar is only useful for multi-platform support

"integration" is often used when talking about a services which "seamlessly integrate" with other tools and technologies
Examples: Slack, Monday, SalesForce, Asana, Zapier, PayPal (just mentioning the first ones I found online)

We also put "integration" into context into the card text itself

Do you have a better term to propose?

**Comment by smolinari** [comment]
The platforms are the OSes, devices and browsers, where the applications can run. PWA, SSR, SPA, BEX isn't what is being noted as Quasar covering in terms of platforms. Sure, those are different modes of Quasar, but they are for the browser and mobile platforms.  

As I noted above, the better word is platforms. "One code base, multiple platforms"

Scott

**Comment by IlCallo** [comment]
Ok, let's discuss this with the team, we don't believe pushing on "platforms" instead of focusing on "integrations" will do any good, also seeing the ideas Jeff shared against using multi-platform in general (which is still used into the catchphrase)

Since we mention "integrations" there, we could also use the new page to highlight some important AEs from the ecosystem (eg. SSG one, Cypress one, etc) as Jeff asked
We planned to do it on the docs homepage, but this could be another way to give more prominence to AEs
