### ISSUE TITLE
Improve '/' icon style in searchbox

### ISSUE THREAD

**Issue by NiccoloMenozzi** [dreamonkey/quasar#25]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Maybe change the '/' icon in the general searchbox with something aligned to the page style (not a priority right now).

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

[](https://quasar.beget.it/)

**Comment by IlCallo** [comment]
The current style was my personal request, and is a native browser visualization (changes if you're in Safari, Chrome, etc)
I wouldn't change this, as it's pretty standard on other frameworks docs too

**Comment by NiccoloMenozzi** [comment]
got it.
