### ISSUE TITLE
Support brand mode, light mode and dark mode

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#36]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Use light-mode for header into the docs, until we have a proper working dark mode for that part too
At a first impression the contrast looks too stark and we may want to avoid it

Scott, Evert and others agreed on this, Evert suggested to use the light mode we have for the landing footer instead
Luke suggested to do A/B testing, even tho I don't think we'll have time to do it 😅 

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Docs

**Comment by smolinari** [comment]
Screens:

Not so good:

![image](https://user-images.githubusercontent.com/3314957/153275145-c1cc3993-fc41-4468-a686-7c29e482dbad.png)


Better:

![image](https://user-images.githubusercontent.com/3314957/153275091-d9d735ef-cd0a-4f2c-a7da-2d8ff03204fa.png)

Scott

**Comment by IlCallo** [comment]
@smolinari will take care of giving a shot to add dark mode.
Only on docs, there should be a button expanding into a drop down menu (or dropdown select of some kind), allowing to switch between "brand mode" (dark header, light content), light mode and dark mode. Brand mode should be the default.
The user choice must be stored into local storage

**Comment by smolinari** [comment]
I'm going to add dark and light mode and only a switch between the two. If you want to add in the dark "branded" header with the light background as another selection after I finish the dark mode @IlCallo, then by all means, be my guest. 

Scott
