### ISSUE TITLE
Update footer for medium viewports

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#45]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

On viewport like iPad Air the footer must be improved: less columns in order to have more space for text lines.
Now the pages labels are displayed badly

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Landing

**Comment by n05la3** [comment]
fixed in 660d393
