### ISSUE TITLE
Change shortcut to access search

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#60]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Vue shortcut to access search (`ctrl + K`) seems easier to use, not everyone have num pad and on non-US keyboards `/` is `shift + 7`, which isn't really immediate to use

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Everywhere

**Comment by smolinari** [comment]
I agree.  

Scott

**Comment by IlCallo** [comment]
Let's ask Vue and Laravel ecosystem maintainers about why they choose what they choose, otherwise let's switch to `ctrl + K`

**Comment by IlCallo** [comment]
Vue team reported this explanation

> Ctrl + K is easier on AZERTY
> Otherwise you need to do Ctrl + Shift + :

AZERTY is french keyboard, it seems a legit change to do to me
