### ISSUE TITLE
Remove the line next to the logo

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#71]
Suggestion: remove the line next to the logo. It takes away from the aesthetics of the header. 

![image](https://user-images.githubusercontent.com/3314957/153200460-26386520-2f89-4388-a887-6e9d863b4a09.png)

Scott

**Comment by NiccoloMenozzi** [comment]
It is inspired by the surface of a vehicle or structure covered with plates of some sort. Let's see it as a subtle element evoking the concept that I discussed with Razvan last year. Also it helps encasing the logo: this help further hierarchical sense with the rest of the bar texts. I am aware that it may look excessive/not aesthetic but it has been put there with a reason and I would, at least, leave it there for the testing period and then see if it is actually a problem for a significant majority of people.

**Comment by IlCallo** [comment]
Gonna close this, since it doesn't seem other people have strong opinions on this, but we'll align it with the open drawer line in some way
