### ISSUE TITLE
Blue glowing shadows feel off

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#73]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

From Luke
> Shadow beneath header feels uncomfortable
> the only thing I don't like is the blue shadows, yet I feel this is more of an unwarranted "pet hate"

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Everywhere

**Comment by NiccoloMenozzi** [comment]
It is a subtle detail that was introduced to sustain the brand storytelling and that doesn't impede in any way the UX. We can make it a point of personal taste but branding and design as a process are based upon other kind of feedback. Among other consistency, coherence and meaning. As long as we adhere to the brand we approved with Razvan I think we can skip this, get to the test period and see if it creates unbearable concern among users.

**Comment by IlCallo** [comment]
Ok, closing this for now, we can reopen this if it proves to be a problem by many people
