### ISSUE TITLE
Add icon video into "Why Quasar" header button

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#74]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

From Luke

> Maybe a video icon right here on the docs page 

Seems a good idea to me, we also discussed about how to let people know where to find the introduction video and this seems a good compromise, @NiccoloMenozzi ?

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Everywhere

**Comment by NiccoloMenozzi** [comment]
I get the reason of the icon but I do not agree to add it, at least right now. Icons improve understanding of the content but they also contribute to crowd the space. I would prefer to leave the bar clean as much as possible. We already see that we added a lot of stuff. For a good reason and surely going under a test period, but I would not add unless we get clear signals that it is necessary. Remember that, sometimes, in design less is more. This seems one of these cases, imo.

**Comment by IlCallo** [comment]
Ok, closing this for now, let's see if someone else chip in later on
