### ISSUE TITLE
Tweak slogan font

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#75]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

From Luke

> use a larger, whiter font for Quasar slogan

@NiccoloMenozzi ?

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Landing

**Comment by NiccoloMenozzi** [comment]
ok, once we are done with the final copywriting no problem for me.

**Comment by IlCallo** [comment]
Ok, remove "waiting for feedback" label here when you updated the mockups so we know we can proceed
