### ISSUE TITLE
Use the light header for the docs 

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#77]
IMHO, this simply looks better. 

![image](https://user-images.githubusercontent.com/3314957/153209227-336bcd22-f111-4646-abfd-8f1aefc60c3b.png)

Than this:

 
![image](https://user-images.githubusercontent.com/3314957/153209349-1921a787-d25e-4560-bda0-4c5161259542.png)

Scott

**Comment by IlCallo** [comment]
Can you add these screenshot under the already existing issue? #36

**Comment by smolinari** [comment]
Closing as dupe for https://github.com/dreamonkey/quasar/issues/36

Scott
