### ISSUE TITLE
WHY SHOULD YOUR TEAM CHOOSE QUASAR?

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#78]
This doesn't speak to everyone. Not everyone has a team. I'd suggest writing....

Why should you choose Quasar?

If they have a team, it's a given they'd be looking for their team too. None of the points below it suggest helping a team be better in the end either. 

Scott

**Comment by IlCallo** [comment]
Fine for me, but if IIRC some writings has been preferred to hook in companies, that's why it focuses on teams: there are already many hobbists using Quasar and which will use it anyway, but they're are also the ones with less "sposorship" power

**Comment by smolinari** [comment]
If we are trying to attract more companies, then a lot of other things need to happen. 

Scott

**Comment by IlCallo** [comment]
Can you expand? We kind of tried to hint enterprises Quasar can be appealing for them too, but without going full out to avoid leaving other parts of the community behind, of course is all a matter of tradeoffs

What other things do you suggest can improve the new website, keeping in consideration the objective?

**Comment by smolinari** [comment]
Since this might become public, I'll send you my thoughts per DM.

Scott

**Comment by IlCallo** [comment]
Let's remove "team", we will probably create a specific section later on for teams and enterprises, adding info about TS, automatic testing and other stuff enterprises care more about

**Comment by IlCallo** [comment]
This wasn't actually fixed into last PR, it has been fixed with last commit
