### ISSUE TITLE
Change call to action text for components. 

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#79]
Suggestion: change the text of this button

![image](https://user-images.githubusercontent.com/3314957/153210925-1e936b50-a5d2-483e-a1fc-c6c8f310ebb1.png)

To "Browse Components". 

And in general, where the word "Consult" is used, needs to be rethought.

Scott

**Comment by IlCallo** [comment]
Fine for me, but why so?
Please add some kind of explanation for these type of suggestions, we probably lack some native English context when some wordings are obviously wrong

I guess `consult` is more used as for `paid consulting` instead of something like `consult a bookshelf`?

**Comment by smolinari** [comment]
Consult simply, isn't used like that. You can say something like, Please consult with your layer. But, you wouldn't say, "consult lawyer". It's hard to explain. 🤷 

Scott

**Comment by IlCallo** [comment]
Ok, will change to "Browse components", anyone has other ideas comment below

**Comment by NiccoloMenozzi** [comment]
Fair with "Browse components" if it is correct.
