### ISSUE TITLE
Update initial call to action text

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#80]
![image](https://user-images.githubusercontent.com/3314957/153211979-8ed3c61c-b731-41b5-9c48-92cac690239d.png)

I'd like to suggest.... 

"Tour through the stars" or "Take a tour through the stars"

Scott

**Comment by IlCallo** [comment]
As other wording updates, nothing against it, but can you provide some context on why this is wrong?

**Comment by smolinari** [comment]
Grammatically, it is fine. It just doesn't sound right. Nobody ever says, "take a look across". "Taka a look at" would be more correct, but that is also bland. 

It could also be "Journey through the stars" or "Journey with us through the stars" or "Journey with us to the stars",  but the latter two might be too long.

Scott

**Comment by IlCallo** [comment]
Ok, some of the ones you proposed also feels strange, we'll need to change this before releasing
Would "are you ready to lift off?" be fine instead?

Otherwise let's see if someone else have a better proposal and/or discuss this in a meeting

**Comment by smolinari** [comment]
"Are you ready to lift off?" would be good. 

By the way, in the sense of "lifting off", I'd change the direction of the background stars. Currently they are going up, giving me the feeling I'm falling down. They should go down, so I feel like I'm going up. 😀 

Should I start another issue for that?

Scott

**Comment by IlCallo** [comment]
Yes please

**Comment by smolinari** [comment]
Done!

Scott

**Comment by NiccoloMenozzi** [comment]
No problem for the call to action inside the button. Anything that is correct, fresh and somehow "space-inspiring" is good. Open to valuable proposals. "Are you ready to lift off?" could be a good alternative is something better doesn't surface.
