### ISSUE TITLE
Fix docs background color

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#81]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Docs background color should be `#fafafa`
Currently it's plain white instead, which is color reserved to the drawers
This may also be the reason why the color contrast with the header seems so stark
Related #36 

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Everywhere

**Comment by NiccoloMenozzi** [comment]
Yep, we changed it to make reading less fatiguing for the eyes. Also it create a little contrast with the nav drawer which is good for the spatial division of UI and will help the users' orientation.
