### ISSUE TITLE
Change direction of background stars

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#82]
The idea to change the call to action to "Are you ready to lift off?" is really good and in the sense of "lifting off", I'd like to suggest to change the direction of the background stars. Currently they are going up, giving me the feeling I'm falling or going down. I think they should go down, so I feel like I'm going up. 😀

Scott

**Comment by IlCallo** [comment]
Let's try this out and see how it feels better

**Comment by NiccoloMenozzi** [comment]
Could be a nice change, I agree, I didn't think of it. If it doesn't feel strange for the eye, surely it will add to the storytelling.

**Comment by IlCallo** [comment]
We tried this out, but when inverting the stars the effect resembles too much snow falling, so we reverted the change
Maybe we could use this for some kind of Christmas easter egg later on
