### ISSUE TITLE
Fix the sentence under "Support Quasar"

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#84]
> Working for a company or freelancer? You can contribute, even a
bit and getting something back.

If I knew what the intention is, I'd suggest a better sentence, but I'm uncertain. For sure, the sentence needs improvement. 

Scott

**Comment by IlCallo** [comment]
Jeff also mentioned "Become Sponsor" should become "Become a Sponsor", do you think this is a legit change too?

**Comment by IlCallo** [comment]
You're right, it's not clear

I've always read it as "Are you either working for a company or a freelancer? You can contribute, even with a small amount, and get some perks out of it."
In general, it should push people to contribute with what they can

@NiccoloMenozzi

**Comment by smolinari** [comment]
Ok. Then I'd write this. 

Heading: Become a Sponsor and Support Quasar!

Sub-text: Contributing to Quasar, even with a small amount, will help sustain Quasar's future.... and you can get some perks out of it too.

Scott

**Comment by NiccoloMenozzi** [comment]
We should try to make the titles short and make them sound fresh. Sometimes it's better to trade off a little bit of exhaustiveness to sound less boring/strict/square/cold/repetitive. The current version sounds good to me and Callo got the meaning. Personally, if it doesn't have any specific real grammar error I would not change it. One thing is grammar, another is to be able to play with words to create something more "interesting" and engaging. We are trying to tell a story here, technicism belongs to the docs sections.

I am open to new proposals but they must be a good compromise between meaningfulness, shortness and freshness.

**Comment by IlCallo** [comment]
Change "Become Sponsor" in into "Sponsor" in the header
Change ""SUPPORT QUASAR, BECOME SPONSOR!"" to "SPONSOR QUASAR, HELP THE PROJECT GROW!"
Change the subtitle as "Working for a company? Are you a freelancer? You can contribute, even a
bit, and get something back."

**Comment by IlCallo** [comment]
@smolinari @ldiebold @hawkeye64 what do you think? Are these changes formally correct in English?
You can propose changes if you like, but let's keep this inspirational, it's not about accuracy, but hooking people in

Eg. if we find something fancier than "help the project grow" it would be even better

**Comment by smolinari** [comment]
I think "Sponsor" on its own isn't clear enough. It either needs to be "Become a Sponsor" or "Sponsor Quasar" or something similar. 

I'm not sure what the second one is changing from or to. 

And you have my feedback on the sentence. If the sentence you have is going to stay, then it needs to be

> "Working for a company? Are you a freelancer? You can contribute, even a bit, and even get something back in return."

Scott

**Comment by ldiebold** [comment]
@IlCallo @NiccoloMenozzi 
Agree with @smolinari on both of these.
> even a bit and getting something back

Doesn't really make sense. Even with the goal of being pithy, it looks more like an error than being terse. Perhaps a total restructure:

> "Working for a company? Are you a freelancer? Contribute at any level and Quasar will open some doors for you...

or

> "Working for a company? Are you a freelancer? We've got awesome perks for contributors!

Same with "Become Sponsor", nobody would talk like this and so it makes you read it twice. For that reason, I'd go with:
"Sponsor Quasar"

**Comment by IlCallo** [comment]
@ldiebold check out the updated version here: https://github.com/dreamonkey/quasar/issues/84#issuecomment-1044611809

We were asking feedback on these ones

**Comment by ldiebold** [comment]
> Change "Become Sponsor" in into "Sponsor" in the header

Yes, much better!

> Change ""SUPPORT QUASAR, BECOME SPONSOR!"" to "SPONSOR QUASAR, HELP THE PROJECT GROW!"

I like this, though I prefer the current heading of "Sponsors and Backers"

> Change the subtitle as "Working for a company? Are you a freelancer? You can contribute, even a
bit, and get something back."

Still prefer my restructures of this sentence :slightly_smiling_face:, so one of the following:

>"Working for a company? Are you a freelancer? We've got awesome perks for contributors!

or

> "Working for a company? Are you a freelancer? Contribute at any level and Quasar will open doors for you...

**Comment by IlCallo** [comment]
>> Change ""SUPPORT QUASAR, BECOME SPONSOR!"" to "SPONSOR QUASAR, HELP THE PROJECT GROW!"
>
> I like this, though I prefer the current heading of "Sponsors and Backers"

Trying to include the sponsor and backers thing plus a bit of inspirational stuff, but the resulting sentence is pretty long
Since we changed the first call to action button,  we can put somewhere something about "reaching the stars"

"Join Quasar sponsors and backers: let's reach the stars together!"

I really like the word "crew", but it seems to me we're then inviting people to do contributions, instead of donations
"Join Quasar crew: let's reach the stars together!"

I'd keep the "crew" stuff and use it to replace "maintainers" later on.
Any idea of some inspirational title containing "sponsors and backers" which isn't too long? Like 5-8 words, which is pretty hard since "sponsors and backers" already take 3, unless we go with a plain "Join our sponsors and backers" and cut off the inspirational part (meh, a bit anticlimatic IMO)

> Still prefer my restructures of this sentence slightly_smiling_face, so one of the following:

I see, but the first one seems too much for what we offer right now, unless we change current tiers/add new ones, eg. private repo with previews, etc
While the second one feels somewhat strange to me, it just doesn't ring...
Mind to brainstorm a little bit more on those ones? Otherwise we can do it together into Friday meeting

**Comment by hawkeye64** [comment]
It's looking much better now.

**Comment by IlCallo** [comment]
Ok, let's go with these ones for now, we can change them later if someone has a better idea

- Change "Become Sponsor" in into "Sponsor" in the header
- Change ""SUPPORT QUASAR, BECOME SPONSOR!"" to "SPONSOR QUASAR, HELP THE PROJECT GROW!"
- Change the subtitle as "Working for a company? Are you a freelancer? You can contribute, even a bit, and even get something back in return."

Keep the proposal coming if you have any, changing these text isn't time consuming so it's just a matter of finding the right words

**Comment by ldiebold** [comment]
All look good to me!
