### ISSUE TITLE
Add other "integrations" into integrations page

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#85]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

See from this comment onwards
https://github.com/dreamonkey/quasar/issues/20#issuecomment-1033635741

Jeff proposed to add an AE card too, we could instead keep using "integrations" to describe all modes and major AEs, showing 2 sections in the integrations page
Raz also mentioned some times he planned to extract modes from core, when/if possible

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Landing

**Comment by yusufkandemir** [comment]
We can use "Integrations" as a more generic term on the landing page. Then, on the "Discover Integrations" page, we can show different build modes(_SPA, PWA, SSR, Capacitor, etc._) and also popular app extensions. This way, we can hit two birds with one stone.

**Comment by IlCallo** [comment]
@hawkeye64 can you add the most tech integration AEs we want to highlight here?

**Comment by hawkeye64** [comment]
QCalendar, QMediaPlayer, and QMarkdown are the top ones.

**Comment by IlCallo** [comment]
@NiccoloMenozzi can you update some mockups to display these UI/components AEs? Or shall we just add them as tiles among others?

Some popular not GUI AEs:
- Testing AEs (first-party): I'd mention Cypress and Jest, but directly link to the general testing AEs README: https://github.com/quasarframework/quasar-testing/blob/dev/README.md
- Apollo AE (first-party): https://www.npmjs.com/package/@quasar/quasar-app-extension-apollo
- SSG mode (third-party): https://github.com/freddy38510/quasar-app-extension-ssg

I wouldn't split between fist-party AEs (maintained by the core team) and third party ones for now as there is just one from third parties. 
It would be better to split between GUI ones (adding a component and similar, the ones mentioned by Jeff) and low level tech integration ones

---

I'd also add here Icongenie and [iconexplorer](https://iconexplorer.app/) links in some form, like under a "Ecosystem" page

---

I just noticed we also don't have any way to reach the integration page from the header or drawer

**Comment by yusufkandemir** [comment]
We can add [quasar-extras-svg-icons](https://quasar-extras-svg-icons.netlify.app/) to the ecosystem section. It contains many different and useful SVG icon sets, and is not so easily discoverable, so it would be nice to give it more visibility.

**Comment by IlCallo** [comment]
We have a mockup to implement which includes all stuff mentioned there, we'll implement it as time permits
