### ISSUE TITLE
Change 'meet the Team' into 'Team'

### ISSUE THREAD

**Issue by NiccoloMenozzi** [dreamonkey/quasar#86]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Let's make it shorter. We save space in the bar which helps in smaller viewports. It was something that I wanted to do but as long as development went on I forgot about this.

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

[](https://quasar.beget.it/)

**Comment by smolinari** [comment]
See https://github.com/dreamonkey/quasar/issues/83

Scott

**Comment by IlCallo** [comment]
Fixed in b0f53cc590ec12b39da08c4c776010207aaf6dff
