### ISSUE TITLE
Viewport app bar issue on Chrome MacBook Pro

### ISSUE THREAD

**Issue by NiccoloMenozzi** [dreamonkey/quasar#93]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

The searchbox doesn't display properly on Chrome, on a MacBook Pro viewport.

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

[
](https://quasar.beget.it/docs/integrations)
<img width="1435" alt="Schermata 2022-02-17 alle 15 42 05" src="https://user-images.githubusercontent.com/84564560/154689910-021e6321-51b5-475c-83de-8b050b86d79c.png">

**Comment by IlCallo** [comment]
This should be fixed into #108
