### ISSUE TITLE
Confused tag assignment in components page

### ISSUE THREAD

**Issue by NiccoloMenozzi** [dreamonkey/quasar#94]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Some components are not assigned to the right tags. eg. floating buttons are not among the buttons tag. we need to check them again and correct what is wrong.
<img width="1440" alt="Schermata 2022-02-18 alle 14 22 04" src="https://user-images.githubusercontent.com/84564560/154690493-d0348d92-a90d-47ae-9963-016e43ef1bef.png">

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

[](https://quasar.beget.it/components)

**Comment by IlCallo** [comment]
Fixed into #108
