### ISSUE TITLE
Remove brand resources from nav bar on laptop-like viewports

### ISSUE THREAD

**Issue by NiccoloMenozzi** [dreamonkey/quasar#95]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

Remove the Quasar Brand Resources from the nav bar on viewports of 1440 px (like macbook pro).
It steals space and is not necessary on every viewport.
The link on 2 text lines are bad and we need to reduce the number of viewports in which this happens.
Removing less important links is the first thing we can do.

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

[](https://quasar.beget.it/docs)

<img width="1440" alt="Schermata 2022-02-18 alle 15 14 04" src="https://user-images.githubusercontent.com/84564560/154698674-949dfa59-58be-4863-b7b7-eb8d7f43707f.png">

**Comment by IlCallo** [comment]
Fixed some time ago already
