### ISSUE TITLE
Wrong sponsor content placement in landing page overlapped on small viewports

### ISSUE THREAD

**Issue by NiccoloMenozzi** [dreamonkey/quasar#98]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

On MacBook, on small viewports, content overlaps.

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

[](https://quasar.beget.it/)

<img width="559" alt="Schermata 2022-02-18 alle 15 47 28" src="https://user-images.githubusercontent.com/84564560/154705262-3a940273-9525-4163-b853-6d0da28b31d1.png">

**Comment by IlCallo** [comment]
Fixed in #108
