### ISSUE TITLE
Social icon bottom page cropped badly on landing page

### ISSUE THREAD

**Issue by NiccoloMenozzi** [dreamonkey/quasar#99]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

The orange icon is cropped on the top part on small smartphone viewport. I'm looking at it from a MacBook Pro.

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

[](https://quasar.beget.it/)

<img width="526" alt="Schermata 2022-02-18 alle 15 51 48" src="https://user-images.githubusercontent.com/84564560/154705999-afdec228-fc9d-447a-b31c-3f755cdf7b30.png">

**Comment by IlCallo** [comment]
Closed into #108
